Rails.application.routes.draw do
 post 'signup', to: 'user#signup'
 post 'item', to: 'item#register'
 post 'signin', to: 'user#signin'
 post 'createnews', to: 'news#create'
 get 'getnews', to: 'news#getnews'
 get 'getcoins', to: 'user#getcoins'
 get 'getNotes', to: 'user#getNotes'
 delete 'deleteNote', to: 'user#deleteNote'
 get 'validate', to: 'user#validate'
 get 'personalitems', to: 'user#personalitems'
 put 'dailyUpdate', to: 'user#dailyUpdate'
 get 'getTotal', to: 'user#getTotal'
 post 'updateCoins', to: 'item#update'
 post 'saveNote', to: 'user#saveNote'
 post 'apiKeys', to: 'user#apiKeys'
 get 'getKeys', to: 'user#getKeys'
 get 'getBalances', to: 'user#getBalances'
 post 'buildBot', to: 'user#buildBot'
 get 'getBots', to: 'user#getBots'
 post 'stopTheBot', to: 'user#stopTheBot'

end
